Adding in an evil test

diff --git a/tests/xmir-helper-test.in b/tests/xmir-helper-test.in
--- a/tests/xmir-helper-test.in
+++ b/tests/xmir-helper-test.in
@@ -8,8 +8,18 @@ TESTVALUE=`@CMAKE_BINARY_DIR@/xmir-helper com.mir.test_mirtest_1.2.3 @CMAKE_CURR
 
 if [ $TESTVALUE == ":42" ]; then
 	echo "PASSED"
-	exit 0
 else
 	echo "FAILED"
 	exit 1
+fi
+
+echo -n "Testing an evil XMir helper… "
+
+export UBUNTU_APP_LAUNCH_XMIR_PATH="@CMAKE_CURRENT_SOURCE_DIR@/xmir-mock-evil.sh"
+
+if @CMAKE_BINARY_DIR@/xmir-helper com.mir.test_mirtest_1.2.3 @CMAKE_CURRENT_SOURCE_DIR@/xmir-helper-exec.sh  ; then
+	echo "FAILED"
+	exit 1
+else
+	echo "PASSED"
 fi
